Added tests HW_6
YuriShumanski1980/HerokuAppHW6 pull request #1
Opened 2021-05-03 22:34 UTC by YuriShumanski1980

2021-05-05 14:42 UTC, vchesnakoutest requested changes
please make fixes

2021-05-05 14:42 UTC, vchesnakoutest commented on src/test/java/tests/HerokuAppHW1AddRemoveElements.java
> +public void herokuAppHW1(){
1. не хватает отступов перед объявлением метода
2. добавляем суффикс Test в конце названий тестовых методов (herokuAppHW1Test) - а ещё лучше называем тесты своими именами (то, что они проверяют, например deleteButtonsTest или что-то похожее). Остальные поправь тоже.

2021-05-05 14:42 UTC, vchesnakoutest commented on src/test/java/tests/HerokuAppHW1AddRemoveElements.java
> +        System.out.println(count);
нету ассерта на проверку кол-ва кнопок

2021-05-05 19:43 UTC, YuriShumanski1980 commented
Внесены изменения, согласно замечаниям Валентина.

2021-05-09 18:18 UTC, closed without merging

2021-05-09 18:18 UTC, YuriShumanski1980 commented
нет надобности